### PR TITLE
Add VEIKK A50 device ID

### PR DESCRIPTION
**Pull request by bwrrp**
Hi!

First of all, thanks a lot for your amazing work! I've been searching for quite a while before I found your driver, and then there's suddenly not just working code, but also a very detailed blog post describing it!

I don't own the s640, but have a VEIKK A50 instead. Fortunately, it turned out that simply adding the device ID was enough to get the pen to work, including pressure sensitivity. I did not look into getting the buttons or touchpad on the A50 working yet. I might look into those later, but I think this tiny change may already be helpful to others.

### CODE REVIEW

**Comment by jlam55555** [comment]
Thanks for the pull request!

Although I don't have it on hand, with the A50 as product ID `0x0003`, I guess the A30 must be `0x0002`, so I'll add that in as well (couldn't hurt).

**Comment by jlam55555** [comment]
On second thought, once integration with the A30/A50 begins, I guess I'll have to rename this repo as well, so I'll probably do that as well.

**Comment by Reezlaw** [comment]
Hello, I apologise if this is the wrong place to tell you, but I wanted to let you know that my A50's pressure detection works flawlessly with this driver "out of the box". Cheers

**Comment by KibaGasteiz** [comment]
Just installed the AUR version but the A50 tablet isn't working, the LED reacts when i use the pen on it, but nothing happens on screen, the tablet runs just fine on Windows but can't say the same for Arch at the moment.
May i need to configure something more?
lsusb gives me this: Bus 001 Device 010: ID 2feb:0003 VEIKK.INC A50

When using the configure tool i got this on screen mapping configuration:
`cat: /sys/module/veikk/parameters/bounds_map: No existe el fichero o el directorio`

**Comment by jlam55555** [comment]
That sounds like an old version of the configure tool with a newer version of the driver. I'm not exactly sure when you downloaded the driver from the AUR or the configuration tool, but if it's older than a circa one week ago it wouldn't work with the new updates (e.g., `bounds_map` has been replaced with `screen_size` and `screen_map`). If that's the case, then I'd highly suggest redownloading both the AUR package and also using the [new configuration tool](https://github.com/jlam55555/veikk-linux-driver-gui), just to make sure you're up-to-date with everything.

If not, let me know. Cheers!

**Comment by jlam55555** [comment]
@KibaGasteiz That sounds like an old version of the configure tool with a newer version of the driver. I'm not exactly sure when you downloaded the driver from the AUR or the configuration tool, but if it's older than a circa one week ago it wouldn't work with the new updates (e.g., `bounds_map` has been replaced with `screen_size` and `screen_map`). If that's the case, then I'd highly suggest redownloading both the AUR package and also using the [new configuration tool](https://github.com/jlam55555/veikk-linux-driver-gui), just to make sure you're up-to-date with everything.

If not, let me know. Cheers!

**Pull request merged**
